export default [
  'create-reactivity-system-vuejs-javascript-part-2',
  'create-reactivity-system-vuejs-javascript-part-1',
  'oop-object-oriented-programming-javascript-explanation',
  'how-tailwind-css-help-reduce-workload',
  'create-blog-nuxtjs-tailwind-css-markdown-netlify-part-1',
  'fix-cors-issue-firebase-google-cloud',
  'rebuild-blog-with-nuxtjs-tailwindcss-part-2',
  'rebuild-blog-with-nuxtjs-tailwindcss-part-1',
  'jalur-rendering-penting-link-preload',
  'struktur-html5-part-2',
  'struktur-html5-part-1',
  'seri-optimasi-website',
  'halo-dunia',
]
