<i18n>
{
  "en": {
    "generated_by": "Data generated by",
    "last_update": "Last updated on",
    "total_request": "Total Request",
    "total_size": "Total Size"
  },
  "id": {
    "generated_by": "Data dihasilkan oleh",
    "last_update": "Terakhir diperbarui pada",
    "total_request": "<em>Request</em> Total",
    "total_size": "Ukuran Total"
  }
}
</i18n>

<template>
  <main id="blog-speed" class="max-w-3xl mx-auto">
    <section>
      <h3 class="pt-12 mb-4 text-4xl font-bold text-center">
        {{ $t('speed') }} ⚡️
      </h3>

      <div class="mb-4 text-center">
        {{ $t('generated_by') }}
        <a
          href="https://github.com/mazipan/psi-gh-action"
          target="_blank"
          rel="noopener noreferrer"
          alt="psi-gh-action"
        >
          psi-gh-action
        </a>
      </div>

      <div>
        <div class="px-6 py-4 mb-2">
          <h4 class="mb-4 text-lg md:text-xl font-bold text-center">
            🗓 {{ $t('last_update') }}
            {{ reportData.timestamp.substring(0, 10) }}
          </h4>

          <div
            v-for="report in reportData.reports"
            :key="`${report.url}${report.device}`"
          >
            <div class="speed-card">
              <div class="mb-4 text-center">
                <h4 class="text-lg md:text-xl font-bold">
                  {{ report.url }}
                </h4>
                <small class="capitalize">
                  {{ report.device === 'desktop' ? '💻  ' : '📱  ' }}
                  {{ report.device }}
                </small>
              </div>
              <div class="mb-4 grid grid-cols-2 md:grid-cols-4">
                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>PERF</small>
                  <div
                    :class="`text-4xl font-bold ${getPerfColorClass(
                      report.perf
                    )}`"
                  >
                    {{ report.perf * 100 }}
                  </div>
                </div>

                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>FID</small>
                  <div>
                    <span
                      :class="`text-4xl font-bold ${getFIDColorClass(
                        report.fid
                      )}`"
                    >
                      {{ report.fid }}
                    </span>
                    <small class="text-lg md:text-xl font-bold">ms</small>
                  </div>
                </div>

                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>LCP</small>
                  <div>
                    <span
                      :class="`text-4xl font-bold ${getLCPColorClass(
                        report.lcp
                      )}`"
                    >
                      {{ formatValue(report.lcp) }}
                    </span>
                    <small class="text-lg md:text-xl font-bold">s</small>
                  </div>
                </div>

                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>CLS</small>
                  <div
                    :class="`text-4xl font-bold ${getCLSColorClass(
                      report.cls
                    )}`"
                  >
                    {{ formatValue(report.cls) }}
                  </div>
                </div>

                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>FCP</small>
                  <div>
                    <span class="text-4xl font-bold">
                      {{ formatValue(report.fcp) }}
                    </span>
                    <small class="text-lg md:text-xl font-bold">s</small>
                  </div>
                </div>
                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>TTI</small>
                  <div>
                    <span class="text-4xl font-bold">
                      {{ formatValue(report.tti) }}
                    </span>
                    <small class="text-lg md:text-xl font-bold">s</small>
                  </div>
                </div>

                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small v-html="$t('total_request')"></small>
                  <div class="text-4xl font-bold">
                    {{ report.req }}
                  </div>
                </div>

                <div class="mb-2 mr-2 px-6 py-4 rounded text-center">
                  <small>{{ $t('total_size') }}</small>
                  <div>
                    <span class="text-4xl font-bold">
                      {{ formatValue(report.size) }}
                    </span>
                    <small class="text-lg md:text-xl font-bold">kB</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <app-profile class="my-12" />
    <app-to-top />
    <app-scroll-indicator />
  </main>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  async asyncData() {
    const availableReports = await import(
      '../psi-reports/available-reports.json'
    )

    const latestReport = await import(
      `../psi-reports/${availableReports.latest}`
    )

    return {
      reportData: latestReport
    }
  },
  data() {
    return {
      reportData: {
        timestamp: new Date().toISOString(),
        reports: []
      }
    }
  },
  // @ts-expect-error
  head() {
    const title = this.$t('speed')
    return {
      title
    }
  },
  computed: {
    formatValue() {
      return (value: number) => value.toFixed(0)
    }
  },
  methods: {
    getPerfColorClass(value: number): string {
      if (value <= 0.49) {
        return 'text-red-600'
      }
      if (value <= 0.89) {
        return 'text-orange-500'
      }

      return 'text-green-500'
    },

    getWebVitalColorClass(value: number, good: number, avg: number): string {
      if (value <= good) {
        return 'text-green-500'
      }

      if (value <= avg) {
        return 'text-orange-500'
      }

      return 'text-red-600'
    },

    getLCPColorClass(value: number): string {
      // @ts-expect-error
      return this.getWebVitalColorClass(value, 2500, 4000)
    },

    getFIDColorClass(value: number): string {
      // @ts-expect-error
      return this.getWebVitalColorClass(value, 100, 300)
    },

    getCLSColorClass(value: number): string {
      // @ts-expect-error
      return this.getWebVitalColorClass(value, 0.1, 0.25)
    }
  }
})
</script>

<style lang="postcss">
/* purgecss start ignore */
.speed-card {
  @apply mb-4 py-4 rounded overflow-hidden shadow relative;
  background-color: var(--card-bg);
}
/* purgecss end ignore */
</style>
